/* help */
help_show:-
        name(X),
        write('Hello,'),
        write(X),
        write(' !'),n1,
        write('Ayo mulai perburuanmu!'),n1,
        write('Berikut ini adalah aksi yang bisa kamu lakukan!'),n1,
        write('1. start'),n1,
        write('2. help'),n1,
        write('3. quit'),n1,
        write('4. w'),n1,
        write('   untuk bergerak ke atas'),n1,
        write('5. a'),n1,
        write('   untuk bergerak ke kiri'),n1,
        write('6. s'),n1,
        write('   untuk bergerak ke bawah'),n1,
        write('7. d'),n1,
        write('   untuk bergerak ke kanan'),n1,
        write('8. map'),n1,
        write('9. heal(pokemon)'),n1,
        write('10. status'),n1,
        write('11. save'),n1,
        write('12. load'),n1,!.
