/* help */
help :-
        write('Valid commands are provided below:'),nl,
        write('1. w -> '),
        write('move up'),nl,
        write('2. a -> '),
        write('move left'),nl,
        write('3. s -> '),
        write('move down'),nl,
        write('4. d -> '),
        write('move right'),nl,
        write('5. map'),nl,
        write('6. heal'),nl,
        write('7. pick (num_inventory_pokemon)'),nl,
        write('8. attack'),nl,
        write('9. specialAttack'),nl,
        write('10. run'),nl,
        write('11. capture'),nl,
        write('12. drop (num_inventory_pokemon)'),nl,
        write('13. status'),nl,
        write('14. save'),nl,
        write('15. load'),nl,
        write('16. help'),nl,
        write('17. quit'),nl,!.
