/* help */
help :-
        /* name(X), */
        write('Hello'),
        /* write(X), */
        write('!'),nl,
        write('Ayo mulai perburuanmu!'),nl,
        write('Berikut ini adalah aksi yang dapat kamu lakukan:'),nl,
        write('1. start'),nl,
        write('2. help'),nl,
        write('3. quit'),nl,
        write('4. w -> '),
        write('untuk bergerak ke atas'),nl,
        write('5. a -> '),
        write('untuk bergerak ke kiri'),nl,
        write('6. s -> '),
        write('untuk bergerak ke bawah'),nl,
        write('7. d -> '),
        write('untuk bergerak ke kanan'),nl,
        write('8. map'),nl,
        write('9. heal'),nl,
        write('10. pick (pokemon)'),nl,
        write('11. attack'),nl,
        write('12. specialAttack'),nl,
        write('13. run'),nl,
        write('14. capture (pokemon)'),nl,
        write('15. drop (pokemon)'),nl,
        write('16. status'),nl,
        write('17. save'),nl,
        write('18. load'),nl,!.
